using System.Collections.Generic;
using EDActivityOverlay.Services;

namespace EDActivityOverlay.Services.Engineering;

/// <summary>
/// Русские названия инженерных сущностей из локализации Coriolis.
/// Источник: EDCD/coriolis src/app/i18n/ru.json (MIT).
/// </summary>
internal static class CoriolisRussianLocalization
{
    private static readonly IReadOnlyDictionary<string, string> Names =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Adaptive Encyptors Capture"] = "Захват адаптивного шифровальщика",
        ["Auto field mainentance unit"] = "Блок автоматического полевого ремонта",
        ["Bulkheads"] = "Переборки",
        ["Chaff launcher"] = "Разбрасыватель дипольных отражателей",
        ["Chemical Storage Units"] = "Контейнеры для химикатов",
        ["Choke canister"] = "Дроссельная кассета",
        ["Collector limpet controller"] = "Контроллер дронов-сборщиков",
        ["Compact Composites"] = "Спрессованные композиты",
        ["Crystal Shards"] = "Осколки кристаллов",
        ["Detailed surface scanner"] = "Подробный сканер поверхности",
        ["Expanded Capacity"] = "Увеличенная вместимость",
        ["Expanded Capacity Cargo Rack"] = "Грузовой стеллаж увеличенной вместимости",
        ["Feedback cascade (Legacy)"] = "Ответный залп (устаревший)",
        ["Filament Composites"] = "Волокнистые композиты",
        ["Frame shift drive"] = "Рамочно-сместительный двигатель",
        ["Frame shift drive interdictor"] = "FSD-перехватчик",
        ["Fuel scoop"] = "Топливозаборник",
        ["Fuel transfer limpet controller"] = "Контроллер дронов-заправщиков",
        ["Hatch breaker limpet controller"] = "Контроллер дронов-взломщиков трюмов",
        ["Heat Resistant Ceramics"] = "Жаропрочная керамика",
        ["Heat sink launcher"] = "Теплоотводная катапульта",
        ["Hull reinforcement"] = "Набор для усиления корпуса",
        ["Life support"] = "Система жизнеобеспечения",
        ["Peculiar Shield Frequency Data"] = "Специфические данные о частоте щитов",
        ["Plasma slug (Legacy)"] = "Плазменный рельсовый снаряд (устаревший)",
        ["Point defence"] = "Точечная оборона",
        ["Polonium"] = "Полоний",
        ["Power distributor"] = "Распределитель питания",
        ["Power plant"] = "Силовая установка",
        ["Prospector limpet controller"] = "Контроллер дронов-геологоразведчиков",
        ["Refinery"] = "Очиститель",
        ["Sensors"] = "Сенсоры",
        ["Shield booster"] = "Усилитель щита",
        ["Shield cell bank"] = "Щитонакопитель",
        ["Shield generator"] = "Щитогенератор",
        ["Super penetrator (Legacy)"] = "Модуль сверхпробития (устаревший)",
        ["Tempered Alloys"] = "Закалённые сплавы",
        ["Thrusters"] = "Маневровые двигатели",
        ["Wake scanner"] = "Сканер следа FSD",
        ["Weapon"] = "Оружие",
        ["Aberrant Shield Pattern Analysis"] = "Анализ аномального поведения щита",
        ["Abnormal Compact Emissions Data"] = "Аномальные компактные данные об излучении",
        ["Adaptive Encryptors Capture"] = "Захват адаптивного шифровальщика",
        ["Ammo capacity"] = "Вместимость магазина",
        ["Angled Plating"] = "Угловая броня",
        ["Anomalous Bulk Scan Data"] = "Аномальный массив данных сканирования",
        ["Anomalous FSD Telemetry"] = "Аномальная телеметрия FSD",
        ["Antimony"] = "Сурьма",
        ["Armoured"] = "Бронированный",
        ["Arsenic"] = "Мышьяк",
        ["Atypical Disrupted Wake Echoes"] = "Атипичное эхо поврежденного следа",
        ["Atypical Encryption Archives"] = "Нетипичные архивы шифрования",
        ["Auto loader"] = "Автоматическая система заряжения",
        ["Biotech Conductors"] = "Биотехнические проводники",
        ["Blast Block"] = "Блокировка взрыва",
        ["Blast resistant"] = "Взрывостойкий",
        ["Boss Cells"] = "Босс-ячейки",
        ["Cadmium"] = "Кадмий",
        ["Carbon"] = "Углерод",
        ["Charge enhanced"] = "Быстрозаряжающийся",
        ["Chemical Distillery"] = "Оборудование для перегонки химикатов",
        ["Chemical Manipulators"] = "Манипуляторы для работы с химикатами",
        ["Chemical Processors"] = "Оборудование для химобработки",
        ["Chromium"] = "Хром",
        ["Classified Scan Databanks"] = "Засекреченные базы данных сканирования",
        ["Classified Scan Fragment"] = "Засекреченные фрагменты данных сканирования",
        ["Clean"] = "«Чистая» донастройка",
        ["Cluster Capacitors"] = "Кассетные конденсаторы",
        ["Compound Shielding"] = "Многоступенчатая защита",
        ["Concordant sequence"] = "Последовательность координации",
        ["Conductive Ceramics"] = "Проводящая керамика",
        ["Conductive Components"] = "Проводящие компоненты",
        ["Conductive Polymers"] = "Проводящие полимеры",
        ["Configurable Components"] = "Настраиваемые компоненты",
        ["Core Dynamics Composites"] = "Композиты Core Dynamics",
        ["Corrosive shell"] = "Разъедающие припасы",
        ["Cracked Industrial Firmware"] = "Взломанные промышленные микропрограммы",
        ["Datamined Wake Exceptions"] = "Исключения из глубинного анализа данных следа",
        ["Dazzle shell"] = "Ослепляющие снаряды",
        ["Decoded Emission Data"] = "Расшифрованные данные об излучении",
        ["Deep Charge"] = "Заряд повышенной мощности",
        ["Deep Plating"] = "Утолщённая броня",
        ["Dirty"] = "«Грязная» донастройка",
        ["Dispersal field"] = "Рассеивающее поле",
        ["Distorted Shield Cycle Recordings"] = "Повреждённые цикличные записи щита",
        ["Divergent Scan Data"] = "Неформатные данные сканирования",
        ["Double Braced"] = "Двойная прочность",
        ["Double shot"] = "Двойной выстрел",
        ["Drag Drives"] = "Ускорители",
        ["Drag munitions"] = "Замедляющие боеприпасы",
        ["Drive Distributors"] = "Распределители тяги",
        ["Eccentric Hyperspace Trajectories"] = "Аномальные траектории в гиперпространстве",
        ["Efficient"] = "Эффективный",
        ["Electrochemical Arrays"] = "Электрохимические массивы",
        ["Emissive munitions"] = "Эмиссионные припасы",
        ["Engine focused"] = "Фокус на двигатель",
        ["Enhanced low power"] = "Улучшенное энергосбережение",
        ["Exceptional Scrambled Emission Data"] = "Исключительные зашифрованные данные об излучении",
        ["Expanded Probe Scanning Radius"] = "Увеличение радиуса сканирования зондов",
        ["Expanded capture arc"] = "Расширенная дуга захвата",
        ["Exquisite Focus Crystals"] = "Отборные фокусировочные кристаллы",
        ["FSD interrupt"] = "Помеха для FSD",
        ["Fast Charge"] = "Быстрый заряд",
        ["Fast scan"] = "Быстрое сканирование",
        ["Faster boot sequence"] = "Ускорение запуска",
        ["Feedback Cascade"] = "Ответный запл",
        ["Flawed Focus Crystals"] = "Поврежденные фокусировочные кристаллы",
        ["Flow Control"] = "Контроль интенсивности",
        ["Focus Crystals"] = "Фокусировочные кристаллы",
        ["Focused"] = "Точный",
        ["Force Block"] = "Усиленная блокировка",
        ["Force shell"] = "Усиленные снаряды",
        ["Galvanising Alloys"] = "Сплавы для гальванизации",
        ["Germanium"] = "Германий",
        ["Grid Resistors"] = "Наборные резисторы",
        ["Heat Conduction Wiring"] = "Теплопроводящие провода",
        ["Heat Dispersion Plate"] = "Теплорассеивающая пластина",
        ["Heat Exchangers"] = "Теплообменные агрегаты",
        ["Heat Vanes"] = "Тепловые заслонки",
        ["Heavy duty"] = "Надёжный",
        ["Hi-Cap"] = "Высокая ёмкость",
        ["High Density Composites"] = "Высокоплотностные композиты",
        ["High capacity"] = "Вместительный магазин",
        ["High charge capacity"] = "Высокоёмкий",
        ["High yield shell"] = "Снаряд большой мощности",
        ["Hybrid Capacitors"] = "Гибридные конденсаторы",
        ["Imperial Shielding"] = "Имперская защита",
        ["Improvised Components"] = "Кустарные компоненты",
        ["Incendiary rounds"] = "Зажигательные припасы",
        ["Inconsistent Shield Soak Analysis"] = "Неполный анализ поглощения щита",
        ["Increased range"] = "Увеличенная дальность",
        ["Inertial impact"] = "Инерционный удар",
        ["Ion disruptor"] = "Ионный дестабилизатор",
        ["Iron"] = "Железо",
        ["Irregular Emission Data"] = "Нестандартные данные об излучении",
        ["Kinetic resistant"] = "Противокинетический",
        ["Layered Plating"] = "Многослойная броня",
        ["Lightweight"] = "Облегчённый",
        ["Lo-draw"] = "Пониженное потребление",
        ["Long range"] = "Дальнего действия",
        ["Low emissions"] = "Малое излучение",
        ["Manganese"] = "Марганец",
        ["Mass Lock Munition"] = "Боеприпасы с гравитационным захватом",
        ["Mass Manager"] = "Распределитель гравитации",
        ["Mass lock munition"] = "Боеприпасы с гравитационным захватом",
        ["Mechanical Components"] = "Механические компоненты",
        ["Mechanical Equipment"] = "Механическое оборудование",
        ["Mechanical Scrap"] = "Механические отходы",
        ["Mercury"] = "Ртуть",
        ["Military Grade Alloys"] = "Сплавы военного назначения",
        ["Military Supercapacitors"] = "Военные суперконденсаторы",
        ["Modified Consumer Firmware"] = "Изменённые пользовательские микропрограммы",
        ["Modified Embedded Firmware"] = "Изменённые встроенные микропрограммы",
        ["Molybdenum"] = "Молибден",
        ["Monstered"] = "Монстрация",
        ["Multi-servos"] = "Сервосистема",
        ["Multi-weave"] = "Мультипрошивка",
        ["Nickel"] = "Никель",
        ["Niobium"] = "Ниобий",
        ["Open Symmetric Keys"] = "Открытые симметричные ключи",
        ["Overcharged"] = "Усиленный",
        ["Overload munitions"] = "Вызывающие перезагрузку боеприпасы",
        ["Oversized"] = "Сверхразмер",
        ["Penetrator Munitions"] = "Бронебойные боеголовки",
        ["Penetrator Payload"] = "Бронебойные снаряды",
        ["Penetrator payload"] = "Бронебойные снаряды",
        ["Pharmaceutical Isolators"] = "Фармацевтические изоляционные материалы",
        ["Phase Alloys"] = "Фазовые сплавы",
        ["Phasing sequence"] = "Последовательность фазирования",
        ["Phosphorus"] = "Фосфор",
        ["Plasma Slug"] = "Плазменный рельсовый снаряд",
        ["Polymer Capacitors"] = "Полимерные конденсаторы",
        ["Precipitated Alloys"] = "Осаждённые сплавы",
        ["Proprietary Composites"] = "Патентованные композиты",
        ["Proto Heat Radiators"] = "Прототипы теплоизлучателей",
        ["Proto Light Alloys"] = "Опытные лёгкие сплавы",
        ["Proto Radiolic Alloys"] = "Сплавы для изготовления зондов",
        ["Radiant Canister"] = "Светящаяся кассета",
        ["Rapid charge"] = "Быстрая зарядка",
        ["Rapid fire"] = "Скорострельный",
        ["Recycling Cell"] = "Рециркуляционная ячейка",
        ["Refined Focus Crystals"] = "Обработанные фокусировочные кристаллы",
        ["Reflective Plating"] = "Отражающая броня",
        ["Regeneration sequence"] = "Последовательность восстановления",
        ["Reinforced"] = "Усиленный",
        ["Resistance augmented"] = "С универсальной защитой",
        ["Reverberating cascade"] = "Отражённый залп",
        ["Ruthenium"] = "Рутений",
        ["Salvaged Alloys"] = "Захваченные сплавы",
        ["Scramble spectrum"] = "Отключающая сетка",
        ["Screening shell"] = "Заслоняющие снаряды",
        ["Security Firmware Patch"] = "Обновление для защитной микропрограммы",
        ["Selenium"] = "Селен",
        ["Shield Emitters"] = "Щитоизлучатели",
        ["Shielded"] = "Защищённый",
        ["Shielding Sensors"] = "Сенсоры системы экранирования",
        ["Shift-lock canister"] = "Рамоблокирующая кассета",
        ["Short range"] = "Ближнего действия",
        ["Smart rounds"] = "Умные боеприпасы",
        ["Specialised"] = "Адаптивный",
        ["Specialised Legacy Firmware"] = "Специальные микропрограммы предыдущего поколения",
        ["Strange Wake Solutions"] = "Странные расчёты следа",
        ["Stripped Down"] = "Урезанный вариант",
        ["Sturdy"] = "Прочный",
        ["Sulphur"] = "Сера",
        ["Super Capacitors"] = "Суперконденсаторы",
        ["Super Conduits"] = "Сверхпроводники",
        ["Super Penetrator"] = "Модуль сверхпробития",
        ["System focused"] = "Фокус на систему",
        ["Tagged Encryption Codes"] = "Меченные шифровальные коды",
        ["Target lock breaker"] = "Генератор помех для системы захвата цели",
        ["Technetium"] = "Технеций",
        ["Tellurium"] = "Теллур",
        ["Thermal Spread"] = "Рассеивание тепла",
        ["Thermal cascade"] = "Термический залп",
        ["Thermal conduit"] = "Проводник тепла",
        ["Thermal resistant"] = "Термостойкий",
        ["Thermal shock"] = "Тепловой удар",
        ["Thermal vent"] = "Теплоотдача",
        ["Thermic Alloys"] = "Термические сплавы",
        ["Thermo Block"] = "Блокировка тепла",
        ["Tin"] = "Олово",
        ["Tungsten"] = "Вольфрам",
        ["Unexpected Emission Data"] = "Неожиданные данные об излучении",
        ["Unidentified Scan Archives"] = "Неопознанные архивы сканирования",
        ["Untypical Shield Scans"] = "Нетипичные данные сканирования щитов",
        ["Unusual Encrypted Files"] = "Особые зашифрованные файлы",
        ["Vanadium"] = "Ванадий",
        ["Weapon focused"] = "Фокус на орудия",
        ["Wide angle"] = "Широкоугольный",
        ["Worn Shield Emitters"] = "Изношенные щитоизлучатели",
        ["Yttrium"] = "Иттрий",
        ["Zinc"] = "Цинк",
        ["Zirconium"] = "Цирконий",
    };

    public static string Translate(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        if (!LocalizationService.Instance.CurrentLanguage.StartsWith("ru", StringComparison.OrdinalIgnoreCase))
        {
            return value;
        }
        return Names.TryGetValue(value, out string? translated) ? translated : value;
    }
}
